### ISSUE TITLE
PDF Export Error

### ISSUE THREAD

**Issue by visualvibe** [Servoy/smartDocumentEditor#2]
I retrieved an API key via the Servoy Cloud website and entered the key into our application. However, when trying to run the PDF export I get a bunch of errors in the console. Below is the .txt file of the errors.

`ERROR com.servoy.j2db.util.Debug - Error executing a request to http://admin-dev.servoy-cloud.eu:4000/generatePDF with method POST with user: null, workstation: null, domain: null
	at C:\Servoy\servoy.2021.06\dev_workspace\svyUtils$documentEditor\svyDocEditor.js:749
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:542 (test)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:139 (open)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1546 (sendEmail)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1355 (onAction$sendCorrespondence)
org.apache.http.conn.HttpHostConnectException: Connect to admin-dev.servoy-cloud.eu:4000 [admin-dev.servoy-cloud.eu/3.121.245.48, admin-dev.servoy-cloud.eu/35.156.60.18] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at com.servoy.extensions.plugins.http.BaseRequest.executeRequest(BaseRequest.java:239) [http.jar:?]
	at com.servoy.extensions.plugins.http.BaseRequest.js_executeRequest(BaseRequest.java:146) [http.jar:?]
	at com.servoy.extensions.plugins.http.BaseRequest.js_executeRequest(BaseRequest.java:132) [http.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:166) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:292) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1487) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:676) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393) [servoy_debug_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:252) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:197) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:241) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:335) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:324) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:137) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:569) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:84) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:548) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:417) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:96) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:86) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.suspend(EventDispatcher.java:241) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGRuntimeWindow.doOldShow(NGRuntimeWindow.java:549) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.RuntimeWindow.doShow(RuntimeWindow.java:304) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.RuntimeWindow.show(RuntimeWindow.java:298) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.BasicFormController.showForm(BasicFormController.java:2382) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.BasicFormController$JSForm.js_show(BasicFormController.java:2605) [servoy_shared_2021.6.0.3683.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor314.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:166) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:292) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1487) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3534) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:676) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393) [servoy_debug_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:252) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:197) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:241) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:335) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:324) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:137) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:569) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:84) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:548) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:417) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:96) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:86) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:57) [servoy_ngclient_2021.6.0.3683.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[org.apache.httpcomponents.httpclient_4.5.10.v20200830-2311.jar:4.5.10]
	... 72 more
ERROR com.servoy.j2db.util.Debug - Error when getting response body for: unknown request
	at C:\Servoy\servoy.2021.06\dev_workspace\svyUtils$documentEditor\svyDocEditor.js:753
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:542 (test)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:139 (open)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1546 (sendEmail)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1355 (onAction$sendCorrespondence)
java.lang.NullPointerException: Cannot invoke "org.apache.http.HttpResponse.getEntity()" because "this.res" is null
	at com.servoy.extensions.plugins.http.Response.js_getResponseBody(Response.java:134) [http.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:166) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:292) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1487) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:676) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393) [servoy_debug_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:252) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:197) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:241) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:335) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:324) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:137) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:569) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:84) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:548) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:417) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:96) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:86) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.suspend(EventDispatcher.java:241) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGRuntimeWindow.doOldShow(NGRuntimeWindow.java:549) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.RuntimeWindow.doShow(RuntimeWindow.java:304) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.RuntimeWindow.show(RuntimeWindow.java:298) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.BasicFormController.showForm(BasicFormController.java:2382) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.BasicFormController$JSForm.js_show(BasicFormController.java:2605) [servoy_shared_2021.6.0.3683.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor314.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:166) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:292) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1487) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3534) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107) [org.eclipse.dltk.javascript.rhino_2021.6.0.3683.jar:?]
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:676) [servoy_shared_2021.6.0.3683.jar:?]
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393) [servoy_debug_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:252) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:197) [servoy_ngclient_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:241) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:335) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:324) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:137) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:569) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:84) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:548) [servoy_ngclient_2021.6.0.3683.jar:?]
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:417) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:96) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:86) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125) [sablo_2021.6.0.3683.jar:?]
	at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89) [sablo_2021.6.0.3683.jar:?]
	at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:57) [servoy_ngclient_2021.6.0.3683.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
ERROR com.servoy.j2db.util.Debug - Connection Error: 0 with error: 
	at C:\Servoy\servoy.2021.06\dev_workspace\svyUtils$documentEditor\svyDocEditor.js:753
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:542 (test)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\corrSendEmail_dtl.js:139 (open)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1546 (sendEmail)
	at C:\Servoy\servoy.2021.06\dev_workspace\curisNG\forms\correspondence_dtl.js:1355 (onAction$sendCorrespondence)`

**Comment by seanthomasdevlin** [comment]
Hi Bjorn,

This issue will be addressed in:
https://support.servoy.com/browse/SVYX-307
Please subscribe as a "watcher" to receive updates. This GitHub issue will be updated with status changes.

Best,
Sean

**Comment by rvanveen-servoy** [comment]
I think this is more related to, here the url was admin-dev.
https://github.com/Servoy/svyUtils/blob/master/svyUtils%24documentEditor/svyDocEditor.js

In the current version we switched to admin.servoy-cloud.eu.

**Comment by visualvibe** [comment]
Hi Rvanveen,

I switched the URL from admin-dev to admin, and I am still getting the same
error message in my console.
